jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_APPLICATION_NAME: tax-calculator-api
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/calculadora_imposto
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      JWT_SECRET: Cc1TqqOVLIjj/cSggo22/wFZYJpLT5WNnrpwmCgdQK9ruAaSiWSf1D+EqtvlsP393FOOgJcYSnXQBt3yM4/m+Q==
      JWT_EXPIRATION: 3600000

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run tests
        run: mvn test
on: