name: Run Tests on Merge to Developer

on:
  push:
    branches:
      - developer

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permissão de execução ao mvnw
        run: chmod +x mvnw

      - name: Build e rodar testes
        run: ./mvnw test
