name: Run Tests on Merge to Developer

on:
  push:
    branches:
      - developer  # dispara apenas quando houver push na branch developer

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # ou a versão do seu projeto
          distribution: 'temurin'

      - name: Build e rodar testes
        run: ./mvnw test # ou 'mvn test' se você usa Maven instalado diretamente
